### ISSUE TITLE
RuntimeError: wrong dimensionality of the vectors 

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/annlite#172]
Hello, 

I have tried 0.3.12 and I got this strange error when indexing (empty workspace).

RuntimeError: wrong dimensionality of the vectors.
My embedding shape is 768. I backtracked that embeddings are really 768, hnsw is set to 768. 
But annlite.index:_rebuild_index : 
```
for docs in self.documents_generator(cell_id, batch_size=10240):
                    logger.info(f"embedings shape {docs.embeddings.shape}") #added by me
                    x = to_numpy_array(docs.embeddings)
```
gives me embedings shape (100, 128) ... 
I tried to find where this dim 128 come from but without any luck.

Can you please help me ?

Thanks

**Comment by jemmyshin** [comment]
Seems like you already had indexed something and it stores under workspace, could you please check your workspace and remove the index files there?

**Comment by tommykoctur** [comment]
Hi @jemmyshin, there is/was definitely no workspace stored. I double checked it multiple times during debugging.

I found that all your test uses dim = 128 , and this number appeared in my bug. 
Maybe it is somehow somewhere hardcoded. I don't know am lost.

**Comment by numb3r3** [comment]
This is a flow example that works
```
jtype: Flow
version: '1'
with:
  port: 61000
executors:
  - name: indexer
    uses:
      jtype: AnnLiteIndexer
      with:
        n_dim: 768
        limit: 10
      metas:
        py_modules:
          - annlite.executor
    workspace: './workspace'
```

Note that, the default `workspace` folder is actually located at `~/.cache/jina/xxx` folder.  In the this example, the `workspace` is set with a custom path. 

Hope this can help you. If you still have such issue, that's would very helpful for us if you can provide an example of how you use annlite in your application.
